routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

 Route::get('/', function () {
    return view('index');
 });

Route::resource('relators','RelatorController');
Route::resource('modules','ModuleController');
Route::resource('schedules','ScheduleController');
Route::resource('courses','CourseController');
Route::resource('institutions','InstitutionController');
Route::resource('carreers','CarreerController');
Route::resource('teachers','TeacherController');
Route::resource('course_teachers','CourseTeacherController');
//Route::resource('courses','SearchCourseController');
//Route::get('/live_search','LiveSearch@index');
//Route::get('/live_search/action','LiveSearch@action')->name('live_search.action');



//Route::get('/live_search', 'LiveSearch@index');
//Route::get('/live_search/action', 'LiveSearch@action')->name('live_search.action');

//Route::get('/live_search', 'RelatorController@index')->name('relators');

Route::get('/live_search', 'LiveSearch@index');
Route::get('/live_search/action', 'LiveSearch@action')->name('live_search.action');

Route::get('/live_search2', 'LiveSearch2@index');
Route::get('/live_search2/action', 'LiveSearch2@action')->name('live_search2.action');

app/Teacher.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Teacher extends Model
{
    //
    protected $fillable = [
      'carreer_id','rut_doc','nombre_doc','apellido_pat_doc','apellido_mat_doc','correo_doc','telefono_doc'
    ];
}

app/Http/Controllers/TeacherController.php
<?php

namespace App\Http\Controllers;

use App\Teacher;
use Illuminate\Http\Request;

class TeacherController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $teachers = Teacher::latest()->paginate(5);
  
        return view('teachers.index',compact('teachers'))
            ->with('i', (request()->input('page', 1) - 1) * 5);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('teachers.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
         $request->validate([

             "carreer_id"=>'required',
             "rut_doc"=>'required',
             "nombre_doc"=>'required',
             "apellido_pat_doc"=>'required',
             "apellido_mat_doc"=>'required',
             "correo_doc"=>'required',
             "telefono_doc"=>'required',

        ]);
  
        Teacher::create($request->all());
   
        return redirect()->route('teachers.index')
                        ->with('success','teacher creado con exito.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Teacher  $teacher
     * @return \Illuminate\Http\Response
     */
    public function show(Teacher $teacher)
    {
        //
        return view('teachers.show',compact('teacher'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Teacher  $teacher
     * @return \Illuminate\Http\Response
     */
    public function edit(Teacher $teacher)
    {
        //
        return view('teachers.edit',compact('teacher'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Teacher  $teacher
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Teacher $teacher)
    {
        //
         $request->validate([
             'carreer_id'=>'required',
             'rut_doc'=>'required',
             'nombre_doc'=>'required',
             'apellido_pat_doc'=>'required',
             'apellido_mat_doc'=>'required',
             'correo_doc'=>'required',
             'telefono_doc'=>'required',

        ]);
  
        $teacher->update($request->all());
  
        return redirect()->route('teachers.index')
                        ->with('success','teacher updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Teacher  $teacher
     * @return \Illuminate\Http\Response
     */
    public function destroy(Teacher $teacher)
    {
        //
         $teacher->delete();
  
        return redirect()->route('teachers.index')
                        ->with('success','teacher deleted successfully');
    }
}

resources/views/teachers/create.blade.php
@extends('teachers.layout')
  
@section('content')
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Agregar Nuevo Docente</h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('teachers.index') }}">Volver</a>
        </div>
    </div>
</div>
   
@if ($errors->any())
    <div class="alert alert-danger">
        <strong>Whoops!</strong> There were some problems with your input.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
   
<form action="{{ route('teachers.store') }}" method="POST">
    @csrf
  
     <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>carreer_id:</strong>
                <input type="text" name="carreer_id" class="form-control" placeholder="carreer_id">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Rut:</strong>
                <input type="text" name="rut_doc" class="form-control" placeholder="rut_doc">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Nombre:</strong>
                <input type="text" name="nombre_doc" class="form-control" placeholder="nombre_doc">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Apellido Paterno:</strong>
                <input type="text" name="apellido_pat_doc" class="form-control" placeholder="apellido_pat_doc">
            </div>
        </div>
        </div>

        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Apellido Materno:</strong>
                <input type="text" name="apellido_mat_doc" class="form-control" placeholder="apellido_mat_doc">
            </div>
        </div>

        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Correo:</strong>
                <input type="text" name="correo_doc" class="form-control" placeholder="correo_doc">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Telefono:</strong>
                <input type="text" name="telefono_doc" class="form-control" placeholder="telefono_doc">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Subir</button>
        </div>
    </div>
   
</form>
@endsection

resources/views/teachers/edit.blade.php
@extends('teachers.layout')
   
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Edit Relators</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('teachers.index') }}"> Back</a>
            </div>
        </div>
    </div>
   
    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
  
    <form action="{{ route('teachers.update',$teacher->id) }}" method="POST">
        @csrf
        @method('PUT')
   
         <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>carreer_id:</strong>
                    <input type="text" name="carreer_id" value="{{ $teacher->carreer_id}}" class="form-control" placeholder="carreer_id">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Rut:</strong>
                    <input type="text" name="rut_doc" value="{{ $teacher->rut_doc}}" class="form-control" placeholder="rut_doc">
                </div>
            </div>

            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>nombre:</strong>
                    <input type="text" name="nombre_doc" value="{{ $teacher->nombre_doc}}" class="form-control" placeholder="nombre_doc">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Apellido Paterno:</strong>
                    <input type="text" name="apellido_pat_doc" value="{{ $teacher->apellido_pat_doc }}" class="form-control" placeholder="apellido_pat_doc">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Apellido Materno:</strong>
                    <input type="text" name="apellido_mat_doc" value="{{ $teacher->apellido_mat_doc}}" class="form-control" placeholder="apellido_mat_doc">
                </div>
            </div>

            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Correo:</strong>
                    <input type="text" name="correo_doc" value="{{ $teacher->correo_doc }}" class="form-control" placeholder="correo_doc">
                </div>
            </div>



            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Telefono:</strong>
                    <input type="text" name="telefono_doc" value="{{ $teacher->telefono_doc }}" class="form-control" placeholder="telefono_doc">
                </div>
            </div>

            

            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
              <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>
   
    </form>
@endsection

resources/views/teachers/index.blade.php
@extends('teachers.layout')
 
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Capacitación Docente</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-success" href="{{ route('teachers.create') }}"> Crear nuevo teacher</a>
            </div>
        </div>
    </div>
   
    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif
   
    <table class="table table-bordered">
        <tr>
            <th>No</th>
            <th>Rut</th>
            <th>carreer_id</th>
            <th>Nombre</th>
            <th>Apellido Paterno</th>
            <th>Apellido Materno</th>
            <th>Correo</th>
            <th>Telefono</th>
            <th width="280px">Acciones</th>
        </tr>
        @foreach ($teachers as $teacher)
        <tr>
            <td>{{ ++$i }}</td>
            <td>{{ $teacher->carreer_id}}</td>
            <td>{{ $teacher->rut_doc}}</td>
            <td>{{ $teacher->nombre_doc}}</td>
            <td>{{ $teacher->apellido_pat_doc}}</td>
            <td>{{ $teacher->apellido_mat_doc}}</td>
            <td>{{ $teacher->correo_doc}}</td>
            <td>{{ $teacher->telefono_doc}}</td>
            <td>
                <form action="{{ route('teachers.destroy',$teacher->id) }}" method="POST">
   
                    <a class="btn btn-info" href="{{ route('teachers.show',$teacher->id) }}">Mostrar</a>
    
                    <a class="btn btn-primary" href="{{ route('teachers.edit',$teacher->id) }}">Editar</a>
   
                    @csrf
                    @method('DELETE')
      
                    <button type="submit" class="btn btn-danger">Borrar</button>
                </form>
            </td>
        </tr>
        @endforeach
    </table>
  
    {!! $teachers->links() !!}
      
@endsection

resources/views/teachers/layout.blade.php
<!DOCTYPE html>
<html>
<head>
    <title>CAPACITACION DOCENTE</title>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha/css/bootstrap.css" rel="stylesheet">
</head>
<body>
  
<div class="container">

    @yield('content')
    
</div>
   
</body>
</html>

resources/views/teachers/show.blade.php
@extends('teachers.layout')
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2> Relator</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('teachers.index') }}">Volver</a>
            </div>
        </div>
    </div>
   
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>carreer_id:</strong>
                {{ $teacher->carreer_id }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Rut:</strong>
                {{ $teacher->rut_doc }}
            </div>
        </div>
         <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Nombre:</strong>
                {{ $teacher->nombre_doc }}
            </div>
        </div>
         <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Apellido Paterno:</strong>
                {{ $teacher->apellido_pat_doc }}
            </div>
        </div>
         <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Apellido Materno:</strong>
                {{ $teacher->apellido_mat_doc }}
            </div>
        </div>
         <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Correo:</strong>
                {{ $teacher->correo_doc}}
            </div>
        </div>
         <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Telefono_rel:</strong>
                {{ $teacher->telefono_doc}}
            </div>
        </div>
        
    </div>
@endsection