routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

 Route::get('/', function () {
    return view('index');
 });

Route::resource('relators','RelatorController');
Route::resource('modules','ModuleController');
Route::resource('schedules','ScheduleController');
Route::resource('courses','CourseController');
Route::resource('institutions','InstitutionController');
Route::resource('carreers','CarreerController');
Route::resource('teachers','TeacherController');
Route::resource('course_teachers','CourseTeacherController');
//Route::resource('courses','SearchCourseController');
//Route::get('/live_search','LiveSearch@index');
//Route::get('/live_search/action','LiveSearch@action')->name('live_search.action');



//Route::get('/live_search', 'LiveSearch@index');
//Route::get('/live_search/action', 'LiveSearch@action')->name('live_search.action');

//Route::get('/live_search', 'RelatorController@index')->name('relators');

Route::get('/live_search', 'LiveSearch@index');
Route::get('/live_search/action', 'LiveSearch@action')->name('live_search.action');

Route::get('/live_search2', 'LiveSearch2@index');
Route::get('/live_search2/action', 'LiveSearch2@action')->name('live_search2.action');

app/Institution.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Institution extends Model
{
    //
     protected $fillable=[

	    	'nombre_ins',
	    	
	    	
	    ];


	    public function carreer()
	{

		
	    return $this->hasMany(Carreer::class);

	}
}

app/Http/Controllers/InstitutionController.php
<?php

namespace App\Http\Controllers;

use App\Institution;
use Illuminate\Http\Request;

class InstitutionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
         $institutions = Institution::latest()->paginate(5);
  
        return view('institutions.index',compact('institutions'))
            ->with('i', (request()->input('page', 1) - 1) * 5);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('institutions.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
         $request->validate([
            

             "nombre_ins"=>'required',
            
        ]);
  
        Institution::create($request->all());
   
        return redirect()->route('institutions.index')
                        ->with('success','Institution creado con exito.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Institution  $institution
     * @return \Illuminate\Http\Response
     */
    public function show(Institution $institution)
    {
        //
        return view('institutions.show',compact('institution'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Institution  $institution
     * @return \Illuminate\Http\Response
     */
    public function edit(Institution $institution)
    {
        //
        return view('institutions.edit',compact('institution'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Institution  $institution
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Institution $institution)
    {
        //
        $request->validate([
             'nombre_ins'=>'required',
             

        ]);
  
        $institution->update($request->all());
  
        return redirect()->route('institutions.index')
                        ->with('success','Institution updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Institution  $institution
     * @return \Illuminate\Http\Response
     */
    public function destroy(Institution $institution)
    {
        //
        $institution->delete();
  
        return redirect()->route('institutions.index')
                        ->with('success','Institution deleted successfully');
    }
}

resources/views/institutions/create.blade.php
@extends('institutions.layout')
  
@section('content')
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Agregar Nueva Institutions</h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('institutions.index') }}">Volver</a>
        </div>
    </div>
</div>
   
@if ($errors->any())
    <div class="alert alert-danger">
        <strong>Whoops!</strong> There were some problems with your input.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
   
<form action="{{ route('institutions.store') }}" method="POST">
    @csrf
  
     <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>nombre_ins:</strong>
                <input type="text" name="nombre_ins" class="form-control" placeholder="nombre_ins">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Subir</button>
        </div>
        
        
    </div>
   
</form>
@endsection

resources/views/institutions/edit.blade.php
@extends('institutions.layout')
   
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Edit Relators</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('institutions.index') }}"> Back</a>
            </div>
        </div>
    </div>
   
    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
  
    <form action="{{ route('institutions.update',$institution->id) }}" method="POST">
        @csrf
        @method('PUT')
   
         <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Nombre_ins:</strong>
                    <input type="text" name="nombre_ins" value="{{ $institution->nombre_ins}}" class="form-control" placeholder="nombre_ins">
                </div>
            </div>
     <div class="col-xs-12 col-sm-12 col-md-12 text-center">
              <button type="submit" class="btn btn-primary">Submit</button>
            </div>
            
        </div>
   
    </form>
@endsection

resources/views/institutions/index.blade.php
@extends('institutions.layout')
 
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Capacitación Docente</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-success" href="{{ route('institutions.create') }}"> Crear nueva institution</a>
            </div>
        </div>
    </div>
   
    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif
   
    <table class="table table-bordered">
        <tr>
            <th>No</th>
            <th>Nombre_ins</th>
            <th width="280px">Acciones</th>
        </tr>
        @foreach ($institutions as $institution)
        <tr>
            <td>{{ ++$i }}</td>
            <td>{{ $institution->nombre_ins}}</td>
            <td>
                <form action="{{ route('institutions.destroy',$institution->id) }}" method="POST">
   
                    <a class="btn btn-info" href="{{ route('institutions.show',$institution->id) }}">Mostrar</a>
    
                    <a class="btn btn-primary" href="{{ route('institutions.edit',$institution->id) }}">Editar</a>
   
                    @csrf
                    @method('DELETE')
      
                    <button type="submit" class="btn btn-danger">Borrar</button>
                </form>
            </td>
        </tr>
        @endforeach
    </table>
  
    {!! $institutions->links() !!}
      
@endsection

resources/views/institutions/layout.blade.php
<!DOCTYPE html>
<html>
<head>
    <title>CAPACITACION DOCENTE</title>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha/css/bootstrap.css" rel="stylesheet">
</head>
<body>
  
<div class="container">

    @yield('content')
    
</div>
   
</body>
</html>

resources/views/institutions/show.blade.php
@extends('institutions.layout')
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Institution</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('institutions.index') }}">Volver</a>
            </div>
        </div>
    </div>
   
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Institution:</strong>
                {{ $institution->nombre_ins }}
            </div>
        </div>
         
    </div>
        
    
@endsection