routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

 Route::get('/', function () {
    return view('index');
 });

Route::resource('relators','RelatorController');
Route::resource('modules','ModuleController');
Route::resource('schedules','ScheduleController');
Route::resource('courses','CourseController');
Route::resource('institutions','InstitutionController');
Route::resource('carreers','CarreerController');
Route::resource('teachers','TeacherController');
Route::resource('course_teachers','CourseTeacherController');
//Route::resource('courses','SearchCourseController');
//Route::get('/live_search','LiveSearch@index');
//Route::get('/live_search/action','LiveSearch@action')->name('live_search.action');



//Route::get('/live_search', 'LiveSearch@index');
//Route::get('/live_search/action', 'LiveSearch@action')->name('live_search.action');

//Route::get('/live_search', 'RelatorController@index')->name('relators');

Route::get('/live_search', 'LiveSearch@index');
Route::get('/live_search/action', 'LiveSearch@action')->name('live_search.action');

Route::get('/live_search2', 'LiveSearch2@index');
Route::get('/live_search2/action', 'LiveSearch2@action')->name('live_search2.action');

app/Relator.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Relator extends Model
{
    //
    protected $fillable = [
      'rut_rel',
      'nombre_rel',
      'apellido_pat_rel',
      'apellido_mat_rel',
      'correo_rel',
      'telefono_rel',
    ];




    public function course()
	{


		return $this->hasMany(Course::class);
	}


	// public function scopeRelator($query, $rut_rel)
 //    {
 //        if ($rut_rel) 
 //            return $query->orwhere('rut_rel','LIKE',"%$rut_rel%");
 //            # code...
 //        }


	
}

//              "nombre_rel"=>'required',
//              "apellido_pat_rel"=>'required',
//              "apellido_mat_rel"=>'required',
//              "correo_rel"=>'required',
//              "telefono_rel"=>'required',

app/Http/Controllers/RelatorController.php
<?php

namespace App\Http\Controllers;

use App\Relator;
use Illuminate\Http\Request;

class RelatorController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {



        $relators = Relator::latest()->paginate(5);
  
        return view('relators.index',compact('relators'))
            ->with('i', (request()->input('page', 1) - 1) * 5);
    }
   
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('relators.create');
    }
  
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            

             "rut_rel"=>'required',
             "nombre_rel"=>'required',
             "apellido_pat_rel"=>'required',
             "apellido_mat_rel"=>'required',
             "correo_rel"=>'required',
             "telefono_rel"=>'required',

        ]);
  
        Relator::create($request->all());
   
        return redirect()->route('relators.index')
                        ->with('success','Relator creado con exito.');
    }
   
    /**
     * Display the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function show(Relator $relator)
    {
        return view('relators.show',compact('relator'));
        
    }
   
    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function edit(Relator $relator)
    {
        return view('relators.edit',compact('relator'));
    }
  
    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Relator $relator)
    {
        $request->validate([
             'rut_rel'=>'required',
             'nombre_rel'=>'required',
             'apellido_pat_rel'=>'required',
             'apellido_mat_rel'=>'required',
             'correo_rel'=>'required',
             'telefono_rel'=>'required',

        ]);
  
        $relator->update($request->all());
  
        return redirect()->route('relators.index')
                        ->with('success','Relator updated successfully');
    }
  
    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function destroy(Relator $relator)
    {
        $relator->delete();
  
        return redirect()->route('relators.index')
                        ->with('success','Relator deleted successfully');
    }


    //query scope

    
}

resources/views/relators/create.blade.php
@extends('relators.layout')
  
@section('content')
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Agregar Nuevo Docente</h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('relators.index') }}">Volver</a>
        </div>
    </div>
</div>
   
@if ($errors->any())
    <div class="alert alert-danger">
        <strong>Whoops!</strong> There were some problems with your input.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
   
<form action="{{ route('relators.store') }}" method="POST">
    @csrf
  
     <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Rut:</strong>
                <input type="text" name="rut_rel" class="form-control" placeholder="rut_rel">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Nombre:</strong>
                <input type="text" name="nombre_rel" class="form-control" placeholder="nombre_rel">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Apellido Paterno:</strong>
                <input type="text" name="apellido_pat_rel" class="form-control" placeholder="apellido_pat_rel">
            </div>
        </div>
        </div>

        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Apellido Materno:</strong>
                <input type="text" name="apellido_mat_rel" class="form-control" placeholder="apellido_mat_rel">
            </div>
        </div>

        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Correo:</strong>
                <input type="text" name="correo_rel" class="form-control" placeholder="correo_rel">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Telefono:</strong>
                <input type="text" name="telefono_rel" class="form-control" placeholder="telefono_rel">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Subir</button>
        </div>
    </div>
   
</form>
@endsection

resources/views/relators/edit.blade.php
@extends('relators.layout')
   
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Edit Relators</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('relators.index') }}"> Back</a>
            </div>
        </div>
    </div>
   
    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
  
    <form action="{{ route('relators.update',$relator->id) }}" method="POST">
        @csrf
        @method('PUT')
   
         <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Rut:</strong>
                    <input type="text" name="rut_rel" value="{{ $relator->rut_rel}}" class="form-control" placeholder="rut_rel">
                </div>
            </div>

            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>nombre:</strong>
                    <input type="text" name="nombre_rel" value="{{ $relator->nombre_rel}}" class="form-control" placeholder="nombre_rel">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Apellido Paterno:</strong>
                    <input type="text" name="apellido_pat_rel" value="{{ $relator->apellido_pat_rel }}" class="form-control" placeholder="apellido_pat_rel">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Apellido Materno:</strong>
                    <input type="text" name="apellido_mat_rel" value="{{ $relator->apellido_mat_rel}}" class="form-control" placeholder="apellido_mat_rel">
                </div>
            </div>

            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Correo:</strong>
                    <input type="text" name="correo_rel" value="{{ $relator->correo_rel }}" class="form-control" placeholder="correo_rel">
                </div>
            </div>



            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Telefono:</strong>
                    <input type="text" name="telefono_rel" value="{{ $relator->telefono_rel }}" class="form-control" placeholder="telefono_rel">
                </div>
            </div>

            

            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
              <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>
   
    </form>
@endsection

resources/views/relators/index.blade.php
@extends('relators.layout')
 
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Capacitación Docente</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-success" href="{{ route('relators.create') }}"> Crear nuevo relator</a>
            </div>
        </div>
    </div>
   
    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif


   
    <table class="table">
        <tr>
            <th>No</th>
            <th>Rut</th>
            <th>Nombre</th>
            <th>Apellido Paterno</th>
            <th>Apellido Materno</th>
            <th>Correo</th>
            <th>Telefono</th>
            <th width="280px">Acciones</th>
        </tr>
        @foreach ($relators as $relator)
        <tr>
            <td>{{ ++$i }}</td>
            <td>{{ $relator->rut_rel}}</td>
            <td>{{ $relator->nombre_rel}}</td>
            <td>{{ $relator->apellido_pat_rel}}</td>
            <td>{{ $relator->apellido_mat_rel}}</td>
            <td>{{ $relator->correo_rel}}</td>
            <td>{{ $relator->telefono_rel}}</td>
            <td>
                <form action="{{ route('relators.destroy',$relator->id) }}" method="POST">
   
                    <a class="btn btn-info" href="{{ route('relators.show',$relator->id) }}">Mostrar</a>
    
                    <a class="btn btn-primary" href="{{ route('relators.edit',$relator->id) }}">Editar</a>
   
                    @csrf
                    @method('DELETE')
      
                    <button type="submit" class="btn btn-danger">Borrar</button>
                </form>
            </td>
        </tr>
        @endforeach
    </table>
  
    {!! $relators->links() !!}
      
@endsection

resources/views/relators/layout.blade.php
<!DOCTYPE html>
<html>
<head>
    <title>CAPACITACION DOCENTE</title>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha/css/bootstrap.css" rel="stylesheet">
</head>
<body>
  
<div class="container">

    @yield('content')
    
</div>
   
</body>
</html>

resources/views/relators/show.blade.php
@extends('relators.layout')
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2> Relator</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('relators.index') }}">Volver</a>
            </div>
        </div>
    </div>
   
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Rut:</strong>
                {{ $relator->rut_rel }}
            </div>
        </div>
         <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Nombre:</strong>
                {{ $relator->nombre_rel }}
            </div>
        </div>
         <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Apellido Paterno:</strong>
                {{ $relator->apellido_pat_rel }}
            </div>
        </div>
         <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Apellido Materno:</strong>
                {{ $relator->apellido_mat_rel }}
            </div>
        </div>
         <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Correo:</strong>
                {{ $relator->correo_rel}}
            </div>
        </div>
         <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Telefono_rel:</strong>
                {{ $relator->telefono_rel}}
            </div>
        </div>
        
    </div>
@endsection