routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

 Route::get('/', function () {
    return view('index');
 });

Route::resource('relators','RelatorController');
Route::resource('modules','ModuleController');
Route::resource('schedules','ScheduleController');
Route::resource('courses','CourseController');
Route::resource('institutions','InstitutionController');
Route::resource('carreers','CarreerController');
Route::resource('teachers','TeacherController');
Route::resource('course_teachers','CourseTeacherController');
//Route::resource('courses','SearchCourseController');
//Route::get('/live_search','LiveSearch@index');
//Route::get('/live_search/action','LiveSearch@action')->name('live_search.action');



//Route::get('/live_search', 'LiveSearch@index');
//Route::get('/live_search/action', 'LiveSearch@action')->name('live_search.action');

//Route::get('/live_search', 'RelatorController@index')->name('relators');

Route::get('/live_search', 'LiveSearch@index');
Route::get('/live_search/action', 'LiveSearch@action')->name('live_search.action');

Route::get('/live_search2', 'LiveSearch2@index');
Route::get('/live_search2/action', 'LiveSearch2@action')->name('live_search2.action');

resources/views/courses/create.blade.php
@extends('courses.layout')
  
@section('content')


<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Agregar Nuevo Docente</h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('courses.index') }}">Volver</a>
        </div>
    </div>
</div>
   
@if ($errors->any())
    <div class="alert alert-danger">
        <strong>Whoops!</strong> There were some problems with your input.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
   
<form action="{{ route('courses.store') }}" method="POST">
    @csrf
  
     <div class="row">

        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>module_id:</strong>
                <input type="text" name="module_id" class="form-control" placeholder="module_id">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>relator_id:</strong>
                <input type="text" name="relator_id" class="form-control" placeholder="relator_id">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>schedule_id:</strong>
                <input type="text" name="schedule_id" class="form-control" placeholder="schedule_id">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>nombre_cur:</strong>
                <input type="text" name="nombre_cur" class="form-control" placeholder="nombre_cur">
            </div>
        </div>
        

        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>modalidad_cur:</strong>
                <input type="text" name="modalidad_cur" class="form-control" placeholder="modalidad_cur">
            </div>
        </div>

        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Duracion:</strong>
                <input type="text" name="duracion_cur" class="form-control" placeholder="duracion_cur">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>sala_cur:</strong>
                <input type="text" name="sala_cur" class="form-control" placeholder="sala_cur">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Subir</button>
        </div>
    </div>
    </div>
   
</form>
@endsection

resources/views/courses/edit.blade.php
@extends('courses.layout')
   
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Edit Course</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('courses.index') }}"> Back</a>
            </div>
        </div>
    </div>
   
    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
  
    <form action="{{ route('courses.update',$course->id) }}" method="POST">
        @csrf
        @method('PUT')
   
         <div class="row">
            

            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Module:</strong>
                    <input type="text" name="module_id" value="{{ $course->module_id}}" class="form-control" placeholder="module_id">
                </div>
            </div>

            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Relator:</strong>
                    <input type="text" name="relator_id" value="{{ $course->relator_id}}" class="form-control" placeholder="relator_id">
                </div>
            </div>  

            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Horarios:</strong>
                    <input type="text" name="schedule_id" value="{{ $course->schedule_id}}" class="form-control" placeholder="schedule_id">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Nombre:</strong>
                    <input type="text" name="nombre_cur" value="{{ $course->nombre_cur}}" class="form-control" placeholder="nombre_cur">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Modalidad:</strong>
                    <input type="text" name="modalidad_cur" value="{{ $course->modalidad_cur}}" class="form-control" placeholder="modalidad_cur">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Duracion:</strong>
                    <input type="text" name="duracion_cur" value="{{ $course->duracion_cur}}" class="form-control" placeholder="duracion_cur">
                </div>
            </div>
           <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>sala:</strong>
                    <input type="text" name="sala_cur" value="{{ $course->sala_cur}}" class="form-control" placeholder="sala_cur">
                </div>
            </div>

            

            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
              <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>
   
    </form>
@endsection

resources/views/courses/index.blade.php
@extends('layout')
 
@section('content')


<table class="table table-striped">

    <a href="{{ route('courses.create') }}" class="btn btn-info">Registrar nuevo curso</a>

<!--buscador de courses-->

{!! Form::open(['route' =>'courses.index','method' =>'GET','class' =>'navbar-form pull-right'])!!}
    <div class="input-group">
    {!!Form::text('nombre_cur',null,['class' => 'form-control','placeholder' => 'Buscar curso..','aria-describedby' => 'search']) !!}
    <span class="input-group-addon" id="search"><span class="glyphicon glyphicon-search" aria-hidden="true"></span></span>
    </div>
    {!! Form::close()!!}

<!--fin de buscador-->


    <hr>
        <thead>
            <th>id</th>
            <th>module_id</th>
            <th>relator_id</th>
            <th>schedule_id</th>
            <th>nombre_cur</th>
            <th>modalidad_cur</th>
            <th>duracion_cur</th>
            <th>sala_cur</th>
        </thead>
        <tbody>
            @foreach($courses as $course)
               <tr>
                <td>{{ $course->id }}</td>
                <td>{{ $course->module->nombre_mod }}</td>
                <td>{{ $course->relator->nombre_rel}}</td>
                <td>{{ $course->schedule->fecha_hor }}</td>
                <td>{{ $course->nombre_cur }}</td>
                <td>{{ $course->modalidad_cur }}</td>
                <td>{{ $course->duracion_cur }}</td>
                <td>{{ $course->sala_cur }}</td>
                <td>
                    <a href="{{ route('courses.edit',$course->id) }}" class="btn btn-warning"><span class="glyphicon glyphicon-wrench" aria-hidden="true"></span></a>

                    <a href="{{ route('courses.destroy',$course->id) }}" onclick="return confirm('¿Seguro que desaeas aliminarlo?')" class="btn btn-danger"><span class="glyphicon glyphicon-remove-circle" aria-hidden="true"></span></a>
                    



                </td>
               </tr>
               @endforeach
        </tbody>
       
    </table>



{{-- <form class="navbar-form navbar-left" role="search" action="{{url('courses.scopeSearch')}}">
 <div class="form-group">
  <input type="text" class="form-control" name='search' placeholder="Buscar ..." />
 </div>
 <button type="submit" class="btn btn-default">Buscar</button>
</form>

    


    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Cursos</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-success" href="{{ route('courses.create') }}"> Crear nuevo Curso</a>
            </div>
        </div>
    </div>
   
    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif
   
    <table class="table table-bordered">
        <tr>
            
            <th>Modulo</th>
            <th>Relator</th>
            <th>Horario</th>
            <th>Nombre Curso</th>
            <th>Modalidad</th>
            <th>Duracion</th>
            <th>sala</th>
            <th width="280px">Acciones</th>
        </tr>
        @foreach ($courses as $course )


        <tr>
            
            <td>{{ $course->nombre_mod}}</td>
            <td>{{ $course->nombre_rel}}</td>
            <td>{{ $course->fecha_hor}}</td>
            <td>{{ $course->nombre_cur}}</td>
            <td>{{ $course->modalidad_cur}}</td>
            <td>{{ $course->duracion_cur}}</td>
            <td>{{ $course->sala_cur}}</td>
            <td>
                <form action="{{ route('courses.destroy',$course->id) }}" method="POST">
   
                    <a class="btn btn-info" href="{{ route('courses.show',$course->id) }}">Mostrar</a>
    
                    <a class="btn btn-primary" href="{{ route('courses.edit',$course->id) }}">Editar</a>
   
                    @csrf
                    @method('DELETE')
      
                    <button type="submit" class="btn btn-danger">Borrar</button>
                </form>
            </td>
        </tr>
        @endforeach
    </table> --}}
  
    {{-- {!! $courses->links() !!} --}}
      
@endsection

resources/views/courses/index2.blade.php
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>


	<table class="table table-striped">
		<thead>
			<th>id</th>
			<th>module_id</th>
			<th>relator_id</th>
			<th>schedule_id</th>
			<th>nombre_cur</th>
			<th>modalidad_cur</th>
			<th>duracion_cur</th>
			<th>sala_cur</th>
		</thead>
		<tbody>
			@foreach($courses as $course)
			   <tr>
			   	<td>{{ $course->id }}</td>
			   	<td>{{ $course->module_id }}</td>
			   	<td>{{ $course->relator_id}}</td>
			   	<td>{{ $course->schedule_id }}</td>
			   	<td>{{ $course->nombre_cur }}</td>
			   	<td>{{ $course->modalidad_cur }}</td>
			   	<td>{{ $course->duracion_cur }}</td>
			   	<td>{{ $course->sala_cur }}</td>
		        <td>
		        	<a href="{{ route('courses.edit',$course->id) }}" class="btn btn-warning"><span class="glyphicon glyphicon-wrench" aria-hidden="true"></span></a>

		        	<a href="{{ route('courses.destroy',$course->id) }}" onclick="return confirm('¿Seguro que desaeas aliminarlo?')" class="btn btn-danger"><span class="glyphicon glyphicon-remove-circle" aria-hidden="true"></span></a>
		        	



		        </td>
		       </tr>
		</tbody>
		</body>
	</table>


</html>

resources/views/courses/layout.blade.php
<!DOCTYPE html>
<html>
<head>
    <title>CAPACITACION DOCENTE</title>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha/css/bootstrap.css" rel="stylesheet">
</head>
<body>
  
<div class="container">

    @yield('content')
    
</div>
   
</body>
</html>

resources/views/courses/show.blade.php
@extends('courses.layout')
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Course</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('courses.index') }}">Volver</a>
            </div>
        </div>
    </div>
   
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Modulo:</strong>
                {{ $course->module_id }}
            </div>
        </div>
         <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Relator:</strong>
                {{ $course->relator_id }}
            </div>
        </div>
         <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Horario:</strong>
                {{ $course->schedule_id }}
            </div>
        </div>
         <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Nombre:</strong>
                {{ $course->nombre_cur }}
            </div>
        </div>
         <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Modalidad:</strong>
                {{ $course->modalidad_cur}}
            </div>
        </div>
         <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Duracion:</strong>
                {{ $course->duracion_cur}}
            </div>
        </div>

        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Sala:</strong>
                {{ $course->sala_cur}}
            </div>
        </div>
        
    </div>
@endsection